### ISSUE TITLE
Make plugin work for Kotlin-DSL

### ISSUE THREAD

**Issue by mattdkerr** [CharlesAHunt/scalapb-gradle-plugin#12]
Gradle 5.0 now has 1.0 of Kotlin DSL, so I've taken a look at using this plugin with that methodology. Currently it's not possible to adapt the samples because the code can't be accessed from Kotlin at all, since the properties are read-only from its viewpoint.

**Comment by lostiniceland** [comment]
Would be great to get this to work. I've just spent quite some time figuring out how the kotlin-dsl can work with this plugin until I found this issue.

**Comment by mattdkerr** [comment]
Yes, I had to work-around it by using the Java generating gradle plugin. I think it would be nice to have it generate real Scala, though. I had some integration issues to figure out with using Circe because of using Kotlin, so I'd imagine there would be other odd issues with Java for some other cases.

**Comment by lostiniceland** [comment]
Is your PR working as expected? If so maybe you can update it with the review comments.
It might be a good idea to merge this into a dedicated branch instead of master and push an alpha artifact to maven.

**Comment by lostiniceland** [comment]
@CharlesAHunt Since I am in need for the Kotlin fix, I've created another PR just containing the bare minimum.
