### ISSUE TITLE
Upgrade ScalaPB to latest version

### ISSUE THREAD

**Issue by zielezin** [CharlesAHunt/scalapb-gradle-plugin#4]
Hello Charles,

Could you upgrade the plugin dependency to use the latest ScalaPB?

**Comment by CharlesAHunt** [comment]
Working on this with a few other dependency upgrades. Should have it ready and tested later this week. :+1:

**Comment by CharlesAHunt** [comment]
Upgraded ScalaPB to the latest 0.6.7.  The latest plugin version is now 1.1.8.

**Comment by zielezin** [comment]
Thank you Charles,

I've noticed that on https://scalapb.github.io/sbt-settings.html they are mentioning version 0.7.1 but with different artifact id: eg:
"com.thesamet.scalapb" %% "compilerplugin" % "0.7.1"
This is consistent with maven repo:

https://mvnrepository.com/artifact/com.thesamet.scalapb/scalapb-runtime
vs
https://mvnrepository.com/artifact/com.trueaccord.scalapb/scalapb-runtime

I think the scapapb got re-branded around end of last year.
Could you please double check this?
