### ISSUE TITLE
unit test fails

### ISSUE THREAD

**Issue by ckchow** [CharlesAHunt/scalapb-gradle-plugin#5]
I guess the TODO above the test implementation refers to this? I get the following when doing `./gradlew test`

    ScalaPBTest:
    Protoc
    - should compile Scala code from the given protos *** FAILED *** (60 milliseconds)
      java.lang.IllegalStateException: the temporary folder has not yet been created

**Comment by CharlesAHunt** [comment]
Thanks for reminding me. I'll get these tests fixed up over the next few days.

**Comment by CharlesAHunt** [comment]
resolved
