### ISSUE TITLE
Update to new ScalaPB version

### ISSUE THREAD

**Issue by lostiniceland** [CharlesAHunt/scalapb-gradle-plugin#6]
The ScalaPB version used by this plugin is deprecated. Please update to 0.7.5 which also uses new artifact coordinates (com.thesamet.scalapb)

**Comment by CharlesAHunt** [comment]
Updated to com.thesamet.scalapb:0.7.4.   The new plugin is published as 1.1.9

https://plugins.gradle.org/plugin/com.charlesahunt.scalapb
